# Generated by Django 3.2.7 on 2021-10-07 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000, 'The Mobile number must contains 10 digits only.'), django.core.validators.MaxValueValidator(9999999999, 'The Mobile number must contains 10 digits only.')]),
        ),
    ]
