# Generated by Django 3.2.7 on 2021-10-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Customer', '0002_auto_20211007_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='Mobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.city'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.country'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.state'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='Full_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
