# Generated by Django 3.2.7 on 2021-10-07 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customerprofile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='pin_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000, 'The PIN code must contains 6 digits only. '), django.core.validators.MaxValueValidator(999999, 'The PIN code must contains 6 digits only. ')]),
        ),
    ]
