# Generated by Django 3.2.7 on 2021-10-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_mobile_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='COD',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='COD',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='COD',
            field=models.BooleanField(null=True),
        ),
    ]
