# Generated by Django 3.2.7 on 2021-10-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
