# Generated by Django 3.2.7 on 2021-10-16 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyProduct', '0002_alter_orderedproduct_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 10, 16)),
        ),
    ]
